import time
import unittest
from random import randint
from datetime import datetime

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

import api


class PatientReport(unittest.TestCase):

    def setUp(self):
        #self.driver = webdriver.Firefox()
        self.driver = webdriver.Chrome()
        self.driver.get('http://test.openelisci.org')
        self.conneting()
        # self.validation()

    def conneting(self):
        driver = self.driver
        username_field = driver.find_element(By.ID, "loginName")
        username_field.clear()
        username_field.send_keys('admin')
        password_field = driver.find_element(By.ID, "password")
        password_field.clear()
        password_field.send_keys('adminADMIN!')
        button = driver.find_element(By.ID, "submitButton")
        button.click()
        # time.sleep(5)

    @api.assert_capture()
    def test_01_use_case1(self):
        # 1. Enter order on Order Entry page. Complete ALL fields. Do not enter results for this order.
        driver = self.driver
        action = ActionChains(driver)
        firstLevelMenu = driver.find_element_by_id("menu_sample")
        action.move_to_element(firstLevelMenu).perform()
        time.sleep(3)
        secondLevelMenu = driver.find_element_by_id("menu_sample_add")
        secondLevelMenu.click()
        time.sleep(3)
        lab_no = driver.find_element_by_xpath("//input[@value='Generate'][@type='button']").click()
        request_date = driver.find_element(By.ID, "requestDate")
        request_date.clear()
        request_date.send_keys('19/09/2019')
        time.sleep(1)
        received_date = driver.find_element(By.ID, "receivedDateForDisplay")
        received_date.clear()
        received_date.send_keys('19/09/2019')
        time.sleep(1)
        received_time = driver.find_element(By.ID,"receivedTime")
        received_time.clear()
        received_time.send_keys('10:12')
        time.sleep(1)
        next_visit_time = driver.find_element(By.ID, "nextVisitDate")
        next_visit_time.clear()
        next_visit_time.send_keys('29/09/2019')
        time.sleep(1)
        select_site_name = driver.find_element_by_id('requesterId')
        options_site_name = select_site_name.find_elements_by_tag_name("option")
        options_site_name[4].click()
        time.sleep(1)
        select_program = driver.find_element_by_id('sampleOrderItems.program')
        options_program = select_program.find_elements_by_tag_name("option")
        options_program[1].click()
        time.sleep(1)
        requester_last_name = driver.find_element(By.ID, "providerLastNameID")
        requester_last_name.clear()
        requester_last_name.send_keys('Mendy')
        time.sleep(1)
        requester_first_name = driver.find_element(By.ID, "sampleOrderItems.providerFirstName")
        requester_first_name.clear()
        requester_first_name.send_keys('Jules')
        time.sleep(1)
        request_phone = driver.find_element(By.ID, "providerWorkPhoneID")
        request_phone.clear()
        request_phone.send_keys('+225-27-19-02-67')
        time.sleep(1)
        fax_number = driver.find_element(By.ID, "providerFaxID")
        fax_number.clear()
        fax_number.send_keys('45')
        time.sleep(1)
        email = driver.find_element(By.ID, "providerEmailID")
        email.clear()
        email.send_keys('mendy32@yahoo.fr')
        time.sleep(1)
        select_patient_status = driver.find_element_by_id('sampleOrderItems.paymentOptionSelection')
        options_patient_status = select_patient_status.find_elements_by_tag_name("option")
        options_patient_status[2].click()
        time.sleep(1)
        urap_number = driver.find_element(By.ID, "billingReferenceNumber")
        urap_number.clear()
        urap_number.send_keys('10')
        time.sleep(1)
        select_patient_status = driver.find_element_by_id('testLocationCodeId')
        options_patient_status = select_patient_status.find_elements_by_tag_name("option")
        options_patient_status[5].click()
        time.sleep(1)
    
        button_sample = driver.find_element(By.ID, "samplesSectionId")
        button_sample.click()
        time.sleep(1)
        select_sample_type = driver.find_element_by_id('sampleTypeSelect')
        options_sample_type = select_sample_type.find_elements_by_tag_name("option")
        options_sample_type[1].click()
        time.sleep(1)
        check2 = driver.find_element(By.ID, "test_0").click()
        time.sleep(1)
        check3 = driver.find_element(By.ID, "test_1").click()
        time.sleep(1)
        check4 = driver.find_element(By.ID, "test_2").click()
        time.sleep(1)
        check5 = driver.find_element(By.ID, "test_3").click()
        time.sleep(1)
        check6 = driver.find_element(By.ID, "test_4").click()
        time.sleep(1)
        check7 = driver.find_element(By.ID, "test_5").click()
        time.sleep(1)
        check8 = driver.find_element(By.ID, "test_6").click()
        time.sleep(1)
        check9 = driver.find_element(By.ID, "test_7").click()
        time.sleep(1)
        check10 = driver.find_element(By.ID, "test_8").click()
        time.sleep(1)
        check11 = driver.find_element(By.ID, "test_9").click()
        time.sleep(1)
        check12 = driver.find_element(By.ID, "test_10").click()
        time.sleep(1)
        check13 = driver.find_element(By.ID, "test_11").click()
        time.sleep(1)
        check14 = driver.find_element(By.ID, "test_12").click()
        time.sleep(1)
        check15 = driver.find_element(By.ID, "test_13").click()
        time.sleep(1)
        check16 = driver.find_element(By.ID, "test_14").click()
        time.sleep(1)
        check18 = driver.find_element(By.ID, "test_15").click()
        time.sleep(1)
        check19 = driver.find_element(By.ID, "test_16").click()
        time.sleep(3)
    
        select_patient_status = driver.find_element_by_id('sampleTypeSelect')
        options_patient_status = select_patient_status.find_elements_by_tag_name("option")
        options_patient_status[2].click()
        time.sleep(2)
        buton = driver.find_element(By.ID, "select_2")
        buton.click()
        time.sleep(2)
        check = driver.find_element(By.ID, "test_0").click()
        time.sleep(1)
        check = driver.find_element(By.ID, "test_1").click()
        time.sleep(1)
        check = driver.find_element(By.ID, "test_2").click()
        time.sleep(1)
        check = driver.find_element(By.ID, "test_3").click()
        time.sleep(5)
    
        select_patient_status = driver.find_element_by_id('sampleTypeSelect')
        options_patient_status = select_patient_status.find_elements_by_tag_name("option")
        options_patient_status[3].click()
        time.sleep(2)
        buton = driver.find_element(By.ID, "select_3")
        buton.click()
        time.sleep(2)
        check2 = driver.find_element(By.ID, "test_0").click()
        time.sleep(1)
        check3 = driver.find_element(By.ID, "test_1").click()
        time.sleep(1)
        check4 = driver.find_element(By.ID, "test_2").click()
        time.sleep(1)
        check5 = driver.find_element(By.ID, "test_3").click()
        time.sleep(1)
        check6 = driver.find_element(By.ID, "test_4").click()
        time.sleep(1)
        check7 = driver.find_element(By.ID, "test_5").click()
        time.sleep(1)
        check8 = driver.find_element(By.ID, "test_6").click()
        time.sleep(1)
        check9 = driver.find_element(By.ID, "test_7").click()
        time.sleep(1)
        check10 = driver.find_element(By.ID, "test_8").click()
        time.sleep(1)
        check11 = driver.find_element(By.ID, "test_9").click()
        time.sleep(1)
        check12 = driver.find_element(By.ID, "test_10").click()
        time.sleep(1)
        check13 = driver.find_element(By.ID, "test_11").click()
        time.sleep(1)
        check14 = driver.find_element(By.ID, "test_12").click()
        time.sleep(1)
        check15 = driver.find_element(By.ID, "test_13").click()
        time.sleep(1)
        check16 = driver.find_element(By.ID, "test_14").click()
        time.sleep(1)
        check18 = driver.find_element(By.ID, "test_15").click()
        time.sleep(1)
        check19 = driver.find_element(By.ID, "test_16").click()
        time.sleep(1)
        check11 = driver.find_element(By.ID, "test_17").click()
        time.sleep(1)
        check12 = driver.find_element(By.ID, "test_18").click()
        time.sleep(1)
        check13 = driver.find_element(By.ID, "test_19").click()
        time.sleep(1)
        check14 = driver.find_element(By.ID, "test_20").click()
        time.sleep(1)
        check15 = driver.find_element(By.ID, "test_21").click()
        time.sleep(1)
        check16 = driver.find_element(By.ID, "test_22").click()
        time.sleep(1)
        check18 = driver.find_element(By.ID, "test_23").click()
        time.sleep(1)
        check19 = driver.find_element(By.ID, "test_24").click()
        time.sleep(5)
    
        button_patient = driver.find_element(By.ID, "orderSectionId")
        button_patient = driver.find_element_by_xpath("//input[@value='+'][@type='button']")
        button_patient.click()
        time.sleep(2)
        subject_number = driver.find_element(By.ID, "subjectNumberID")
        subject_number.clear()
        subject_number.send_keys('40t')
        time.sleep(2)
        national_id = driver.find_element(By.ID, "nationalID")
        national_id.clear()
        national_id.send_keys('3r')
        time.sleep(2)
        patient_last_name = driver.find_element(By.ID, "lastNameID")
        patient_last_name.clear()
        patient_last_name.send_keys('Seck')
        time.sleep(2)
        patient_first_name = driver.find_element(By.ID, "firstNameID")
        patient_first_name.clear()
        patient_first_name.send_keys('Nit')
        time.sleep(2)
        street = driver.find_element(By.ID, "streetID")
        street.clear()
        street.send_keys('Zzzzz')
        time.sleep(2)
        commune = driver.find_element(By.ID, "communeID")
        commune.clear()
        commune.send_keys('Nnnnnnn')
        time.sleep(2)
        city = driver.find_element(By.ID, "cityID")
        city.clear()
        city.send_keys('Ddddddd')
        time.sleep(2)
        phone = driver.find_element(By.ID, "patientPhone")
        phone.clear()
        phone.send_keys('+225-45-07-99-01')
        time.sleep(2)
        select_country = driver.find_element_by_id('healthRegionID')
        options_country = select_country.find_elements_by_tag_name("option")
        options_country[14].click()
        time.sleep(2)
        select_district = driver.find_element_by_id('healthDistrictID')
        options_country = select_district.find_elements_by_tag_name("option")
        options_country[2].click()
        time.sleep(2)
        date_birth = driver.find_element(By.ID, "dateOfBirthID")
        date_birth.clear()
        date_birth.send_keys('25/09/2000')
        time.sleep(15)
        age = driver.find_element(By.ID, "age")
        age.clear()
        age.send_keys('19')
        time.sleep(2)
        select_country = driver.find_element_by_id('genderID')
        options_country = select_country.find_elements_by_tag_name("option")
        options_country[1].click()
        time.sleep(2)
        select_education = driver.find_element_by_id('educationID')
        options_education = select_education.find_elements_by_tag_name("option")
        options_education[1].click()
        time.sleep(2)
        select_maritial = driver.find_element_by_id('maritialStatusID')
        options_maritial = select_maritial.find_elements_by_tag_name("option")
        options_maritial[1].click()
        time.sleep(2)
        select_nationality = driver.find_element_by_id('nationalityID')
        options_nationality = select_nationality.find_elements_by_tag_name("option")
        options_nationality[1].click()
        time.sleep(2)
        specify = driver.find_element(By.ID, "nationalityOtherId")
        specify.clear()
        specify.send_keys('first time')
        time.sleep(5)
        button_save = driver.find_element(By.ID, "saveButtonId")
        button_save.click()
    
        # Generate the Patient Report for this order
        driver = self.driver
        action = ActionChains(driver)
        firstMenuReport = driver.find_element_by_id("menu_reports")
        action.move_to_element(firstMenuReport).perform()
        time.sleep(5)
        secondMenuReport = driver.find_element_by_id("menu_reports_routine")
        action.move_to_element(secondMenuReport).perform()
        time.sleep(5)
        thirdMenuReport = driver.find_element_by_id("menu_reports_status_patient")
        action.move_to_element(thirdMenuReport).perform()
        time.sleep(5)
        fourthMenuReport = driver.find_element_by_id("menu_reports_status_patient.classique")
        fourthMenuReport.click()
        time.sleep(5)
        field_from = driver.find_element(By.ID, "accessionDirect")
        field_from.clear()
        field_from.send_keys('1234519000215')
        time.sleep(3)
        field_to = driver.find_element(By.ID, "highAccessionDirect")
        field_to.clear()
        field_to.send_keys('1234519000215')
        time.sleep(3)
        button_generate = driver.find_element_by_xpath("//input[@value='Generate printable version'][@type='button']")
        button_generate.click()
        time.sleep(5)

  
    @api.assert_capture()
    def test_02_use_case2(self):
        #Go to Modify Order for the same order from Use Case 1 and cancel one test
        driver = self.driver
        action = ActionChains(driver)
        firstLevelMenu = driver.find_element_by_id("menu_sample")
        action.move_to_element(firstLevelMenu).perform()
        time.sleep(3)
        secondLevelMenu = driver.find_element_by_id("menu_sample_edit")
        secondLevelMenu.click()
        time.sleep(3)
        select_search_by = driver.find_element_by_id('searchCriteria')
        options_search_by = select_search_by.find_elements_by_tag_name("option")
        options_search_by[5].click()
        time.sleep(3)
        search_value = driver.find_element(By.ID, "searchValue")
        search_value.clear()
        # search_value.send_keys('1234519000170')
        search_value.send_keys('1234519000148')
        time.sleep(3)
        search_button = driver.find_element(By.ID, "searchButton")
        search_button.click()
        time.sleep(10)
        champ_newNumberOrder = driver.find_element(By.ID, "accessionEdit")
        champ_newNumberOrder.clear()
        # pop up message is generated
        x = '00000' + str(randint(100, 1000))
        champ_newNumberOrder.send_keys(x)
        time.sleep(3)
        champ_nextVisit = driver.find_element(By.ID, "nextVisitDate")
        champ_nextVisit.clear()
        # pop up message is generated
        champ_nextVisit.send_keys('25/09/2019')
        time.sleep(3)
        champ_requesterPhone = driver.find_element(By.ID, "providerWorkPhoneID")
        champ_requesterPhone.clear()
        champ_requesterPhone.send_keys('+225-27-19-02-' + str(randint(10, 99)))
        time.sleep(3)
        champ_requesterLastName = driver.find_element(By.ID, "providerLastNameID")
        champ_requesterLastName.clear()
        #champ_requesterLastName.send_keys('zzzzz' + str(randint(1, 10000)))
        champ_requesterLastName.send_keys('zzzzz'*6 )
        # time.sleep(3)
        # champ_requesterFirstName = driver.find_element(By.ID, "providerLastNameID")
        # champ_requesterFirstName.clear()
        # champ_requesterFirstName.send_keys('terrain')
        time.sleep(3)
        champ_Email = driver.find_element(By.ID, "providerEmailID")
        champ_Email.clear()
        champ_Email.send_keys('abcdef@abcdef.org')
        time.sleep(3)
        select_siteName = driver.find_element_by_id('requesterId')
        options_siteName = select_siteName.find_elements_by_tag_name("option")
        options_siteName[6].click()
        time.sleep(5)
        button_check = driver.find_element_by_xpath("//input[@name='existingTests[10].canceled'][@type='checkbox']")
        button_check.click()
        time.sleep(5)
        button_save = driver.find_element(By.ID, "saveButtonId")
        button_save.click()
        time.sleep(10)

        driver = self.driver
        action = ActionChains(driver)
        firstMenuReport = driver.find_element_by_id("menu_reports")
        action.move_to_element(firstMenuReport).perform()
        time.sleep(5)
        secondMenuReport = driver.find_element_by_id("menu_reports_routine")
        action.move_to_element(secondMenuReport).perform()
        time.sleep(5)
        thirdMenuReport = driver.find_element_by_id("menu_reports_status_patient")
        action.move_to_element(thirdMenuReport).perform()
        time.sleep(5)
        fourthMenuReport = driver.find_element_by_id("menu_reports_status_patient.classique")
        fourthMenuReport.click()
        time.sleep(5)
        field_from = driver.find_element(By.ID, "accessionDirect")
        field_from.clear()
        field_from.send_keys('12345'+x)
        time.sleep(3)
        field_to = driver.find_element(By.ID, "highAccessionDirect")
        field_to.clear()
        field_to.send_keys('12345'+x)
        time.sleep(3)
        button_generate = driver.find_element_by_xpath("//input[@value='Generate printable version'][@type='button']")
        button_generate.click()
        time.sleep(5)

    def tearDown(self):
        self.driver.close()
        self.driver.quit()